// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFgNAZ4aMfD7P3wSg835YGgTxn2Mtk9U',
    appId: '1:612425777202:web:c120cf87d1fef2bd593c2b',
    messagingSenderId: '612425777202',
    projectId: 'login-6dd20',
    authDomain: 'login-6dd20.firebaseapp.com',
    storageBucket: 'login-6dd20.appspot.com',
    measurementId: 'G-YYDSWKKRDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Voc_tXqVoFBM0GV8YtMh59IPZCHvIRM',
    appId: '1:612425777202:android:e2cf1fc4528a155b593c2b',
    messagingSenderId: '612425777202',
    projectId: 'login-6dd20',
    storageBucket: 'login-6dd20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtyBllfYgmY-4xxwNlSi-ikZ2jAn1taQ',
    appId: '1:612425777202:ios:d2b1d03376fbf1f9593c2b',
    messagingSenderId: '612425777202',
    projectId: 'login-6dd20',
    storageBucket: 'login-6dd20.appspot.com',
    iosBundleId: 'com.example.loginTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtyBllfYgmY-4xxwNlSi-ikZ2jAn1taQ',
    appId: '1:612425777202:ios:d2b1d03376fbf1f9593c2b',
    messagingSenderId: '612425777202',
    projectId: 'login-6dd20',
    storageBucket: 'login-6dd20.appspot.com',
    iosBundleId: 'com.example.loginTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXFgNAZ4aMfD7P3wSg835YGgTxn2Mtk9U',
    appId: '1:612425777202:web:4cb944e2852f8d25593c2b',
    messagingSenderId: '612425777202',
    projectId: 'login-6dd20',
    authDomain: 'login-6dd20.firebaseapp.com',
    storageBucket: 'login-6dd20.appspot.com',
    measurementId: 'G-G4VRP7TGCF',
  );
}
